### ISSUE TITLE
Is this repo still maintain ?

### ISSUE THREAD

**Issue by StevenMasini** [oblador/react-native-lightbox#103]
@oblador  Is this repository still alive ?

I can see there is 12 Pull Request waiting for review and the repo hasn't been updated since the 22 Sept 2017.

You have 1 500+ stars also, which means people like this project.
I think it would be a pity to let such a cool project dying.

**Comment by oblador** [comment]
Unfortunately, it's not really active no. I didn't plan on abandoning it, but I've made the realization that this kind of functionality best resides or is tied to some kind of navigation library. I have actually made some work earlier in this direction, but there was a pressy crazy turnover of what was the "default" navigation library – like three changes within a year so I've been waiting for it to stabilize and mature. Currently my bet is on react-navigation which has some plans on adding shared element transitions, but that work has been stalled for half a year at least, so my expectations are low. 

It would however be possible to reduce the scope to what it was originally and just write a custom navigator/transitioner. I have a pretty good idea how I'd approach it and how to make it more performant, but don't have the time to be sole maintainer and at the same time triage issues, write features, documentation etc. Would you be up for helping me out with things like triaging I could revive the repo.

**Comment by peteroid** [comment]
I understand the difficulty of maintaining this kind of library which heavily depends on the navigation library. In my case, I am using both RNN and react-navigation at the same time. When I was trying to customize the lightbox, I did rewrite the lightbox depending on the RNN due to the deep dependency and different props structure. 

However, I am happy to hear more about the future thought about this library as lightbox is now kind of a must for every app which contains any image or video. Previously, I was thinking whether this library could implement something like mentioned in this video: https://youtu.be/7emqc7yf-Zg?t=7m1s to improve the performance.

**Comment by StevenMasini** [comment]
@oblador I do love to help if I can, but I am an ex native iOS developer with only three months experience with React Native and Javascript.

I am not sure what's the deal with `Navigator`, I am myself using React Navigation in my project, but I think it would be sad if this project was a depending on one or another solution.

I might say something stupid, but wouldn't [Modal](https://facebook.github.io/react-native/docs/modal.html) do the job ? It's compatible with both Android/iOS and you can overwrite the transition by just setting `animationType` to none.

But as I said above, I really do love to help. If can do anything I will.

**Comment by oblador** [comment]
Hey @StevenMasini, I've decided to try to take up development again, but start afresh given a lot has changed in the RN world since I started this three years ago (pre android, native animation driver etc). 

I'll try to keep compatibility where it's easy and possible, but will not limit myself to old and imperfect APIs. Next up will be to track the work in a PR and list my requirements and maybe have some discussion around it. 

Is there a way for us to talk directly, like on twitter/email @StevenMasini (and potentially @peteroid)?

**Comment by StevenMasini** [comment]
@oblador Great! I am willing to help, let's do it! My Github and Twitter username are the same. Let's talk there.

PS: I didn't find you, using oblador on Twitter.

**Comment by peteroid** [comment]
@oblador my twitter id is `_peteroid`

**Comment by StevenMasini** [comment]
@oblador @peteroid I will close this issue then. Let's use the [Road to 1.0 (request for comments)](https://github.com/oblador/react-native-lightbox/issues/104#issuecomment-379729532) for now on.
