### ISSUE TITLE
[Performance] Very poor performance on close

### ISSUE THREAD

**Issue by JonathanWi** [oblador/react-native-lightbox#2]
Great plugin, I just have a performance problem (on iPhone 6 & iPhone 5) when closing a lightbox (cover or not). The animation become super laggy and can also make the app crash if closed too fast.

Any idea?

Cheers

**Comment by oblador** [comment]
Hi, 

Thanks for posting this bug report. I can reproduce (although not always!) with the image with the `resizeMode="cover"` prop (the other's seems to be fine). I'm not entirely sure why but it seems iOS will simply kill it. Maybe because it runs out of memory because I always get a memory warning before crash and that's the behavior of iOS when it runs out of memory, but I seldom go above 30-40mb in the example app. It could be that the `Modal` component is buggy, try downgrading to 0.2.0 and see if that helps. About performance, right now the `Animated` lib is JS only, but will soon be run natively which will make the animations much more performant. I'm expecting this in the following months since it's an important feature, but I really don't have any insight, just a wild guess. 

Also try using `resizeMode="contain"` instead (not sure if that actually helps or it's just a coincidence in the example app).

**Comment by JonathanWi** [comment]
Thanks a lot for your very fast answer! 

You were right, contain (but also stretch it seems) looks more steady. I'm looking forward to using your native based plugin!

Cheers
