### ISSUE TITLE
Support for NavigationExperimental

### ISSUE THREAD

**Issue by vdrg** [oblador/react-native-lightbox#33]
I'm using react-native-router-flux and it uses NavigationExperimental, any chance to support it?

Thanks!

**Comment by rgovindji** [comment]
Not sure if this will help you but I was having issues before and thought it was due to react-native-router-flux. Currently I am using react-native-router-flux with react-native v0.22.2 and the component works. I was having issues earlier where I would only see gray boxes but that was because the image height/width were not set when the component rendered. To get around that since I have a dynamic images with various width/heights I created a parent view for each image and set a callback to handleLayout on that view. When the view renders I grab width/height of the view then set width/height of the image and render it within the view.

**Comment by ms88privat** [comment]
does anybody has an example how to setup this?

**Comment by vdrg** [comment]
Actually @rgovindji was right, I had to set the image dimensions beforehand. Thanks!

**Comment by ms88privat** [comment]
@vdrg could you please provide me an example? Are you passing the NavigationExperimental as prop to the component?

Is it possible to trigger this transition with the Actions from router-flux?

Thanks!

**Comment by rgovindji** [comment]
@ms88privat 

I did something like this

```

//Set the width and height of the image after the parent view renders
_handleLayout(event){
 this.refs.photoView.measure((x, y, width, height, px, py) => {
        this.setState({
          imageWidth: width,
          imageHeight: height
        });
      });
}

render(){
  return (
      <View ref='photoView' 
        onLayout={this._handleLayout}
       >
<Image
      source={{ uri: this.props.photo.url }}
      style={{ width: this.state.imageWidth, height: this.state.imageHeight }}/>
      </View>
    );
  }
}
```
