### ISSUE TITLE
Is conflicted with react-native-swiper？

### ISSUE THREAD

**Issue by japinli** [oblador/react-native-lightbox#82]
![image](https://user-images.githubusercontent.com/20606090/30537577-cca60628-9c9c-11e7-8c46-fb448d44716e.png)
when I use it with react-native-swiper, it does not work

**Comment by mikehuebner** [comment]
trying to use it a similar way, you can't use the swiper though because the touch controller takes over for the lightbox. But you also cannot swipe through images, which I'm also trying to fix. The panresponder is only listening for y drags but I can't seem to fix the threshold at which it receives those.
