### ISSUE TITLE
Off-center in lightbox mode?

### ISSUE THREAD

**Issue by psyanite** [oblador/react-native-lightbox#97]
Not sure if a real issue, here's what I'm seeing: 
![capture](https://user-images.githubusercontent.com/24215698/34462100-0fe8fa54-ee90-11e7-8077-2307eb99d192.PNG)

I'm using Expo, I think if the status bar at the top (the OS status bar) is transparent the black misses a bar at the bottom :/

**Comment by koswarabilly** [comment]
i have the same issue

**Comment by koswarabilly** [comment]
go to the library folder in `node_modules` open up `LightboxOverlay.js` on line 19 there will be `open` in `const **styles** ` add `alignItems : 'center',` it will centralize your image, maybe the developer forget to add it. it kind of hack the library but i hope this help.

**Comment by psyanite** [comment]
If the contributors would like to close this issue I'm happy with that, but I'll leave it open for now.

**Comment by hoscarcito** [comment]
You do not need to modify the code, this is related with the resizeMode
In the docs says that you can have different props for the images so you can use different resizeModes for both.
Here's an example:

`` `
const activeProps = {
   resizeMode: 'contain',
   flex: 1,
   width: null
};
       <Lightbox
         activeProps = {activeProps}
         renderContent = {() => renderCarousel (this.items, currentPage)}
       >
`` `
Hope it helps! I hate to modify the library because it struggles with your CI/CD configuration

**Comment by psyanite** [comment]
Sounds like that's a solution, I'm going to close this issue.
